### ISSUE TITLE
dizionari_dati.md = manca una parola da tradurre dallo spagnolo

### ISSUE THREAD

**Issue by cirospat** [ondata/guidaPraticaPubblicazioneCSV#11]
nel file `dizionari_dati.md`
al quart'ultimo punto manca una parola da tradurre
non dimenticare

**Comment by aborruso** [comment]
Sì, ieri avevo creato [questa](https://github.com/ondata/guidaPraticaPubblicazioneCSV/issues/9), per segnare tutte le cose da rivedere

**Comment by aborruso** [comment]
@all-contributors please add @cirospat for content, example
