### ISSUE TITLE
Tradurre anche i nomi colonna

### ISSUE THREAD

**Issue by aborruso** [ondata/guidaPraticaPubblicazioneCSV#22]
@cirospat occhio a cose come `tipo_averia` presente qui https://ondata.github.io/guidaPraticaPubblicazioneCSV/guida/linee_guida_pubblicazione/P04_strutture_dati_verticale_orizzontale/

Creare la versione "italiana".

Non appena fatto, chiudi tu

**Comment by lorenzoperone** [comment]
i nomi ora sono a posto
