### ISSUE TITLE
P15 Campi con coordinate geografiche

### ISSUE THREAD

**Issue by aborruso** [ondata/guidaPraticaPubblicazioneCSV#41]
Verifiche da fare:

- [x] rileggere più volte. In italiano lo scriveresti così?
- [x] tradurre tutto. I nomi dei campi delle tabelle di esempio, eventuali didascalie, ecc..
- [x] verificare link esterni presenti, nel caso aggiornarli
- [x] se si cita altro capitolo nel testo, creare link a quel capitolo

Se lo vuoi tradurre auto assegnati la issue

**Comment by pigreco** [comment]
capitolo aggiunto:

https://ondata.github.io/guidaPraticaPubblicazioneCSV/guida/linee_guida_pubblicazione/P15_campi_con_coordinate_geografiche/
