### ISSUE TITLE
Link utili

### ISSUE THREAD

**Issue by aborruso** [ondata/guidaPraticaPubblicazioneCSV#50]
Verifiche da fare:

- [x] rileggere più volte. In italiano lo scriveresti così?
- [x] tradurre tutto. I nomi dei campi delle tabelle di esempio, eventuali didascalie, ecc..
- [x] verificare link esterni presenti, nel caso aggiornarli
- [x] se si cita altro capitolo nel testo, creare link a quel capitolo

Se lo vuoi tradurre auto assegnati la issue

**Comment by cirospat** [comment]
il link
[Open data FEMP 2019: 40 set di dati che saranno pubblicati dagli enti locali](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/viewer.html?pdfurl=http%3A%2F%2Ffemp.femp.es%2Ffiles%2F3580-1937-fichero%2FDATOS%2520ABIERTOS%2520FEMP%25202019.pdf&clen=29966510)

L'URL al link di sopra non è raggiungibile.
Di cosa si tratta?

**Comment by cirospat** [comment]
vedo che ora al testo
**Open data FEMP 2019: 40 set di dati che saranno pubblicati dagli enti locali**
c'è collegato correttamente il link: http://femp.femp.es/files/3580-1937-fichero/DATOS%20ABIERTOS%20FEMP%202019.pdf

**Comment by aborruso** [comment]
> c'è collegato correttamente il link: http://femp.femp.es/files/3580-1937-fichero/DATOS%20ABIERTOS%20FEMP%202019.pdf

@cirospat grazie!

**Comment by aborruso** [comment]
Questa la chiudiamo, ma ne apro una correlata

**Comment by aborruso** [comment]
@cirospat ho creato questa https://github.com/ondata/guidaPraticaPubblicazioneCSV/issues/77
